# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login

    access_control:
    # require ROLE_ADMIN for /gestion*
        - { path: ^/^(?!login).*, roles: ROLE_USER }