app:
    resource: "@AppBundle/Controller/"
    type:     annotation

api_login_check:
   path: /ressources/login_check

JMSJobQueueBundle:
   resource: "@JMSJobQueueBundle/Controller/"
   type: annotation
   prefix: /gestion/jobs